# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  # Job to print "Hello, World!"
  say-hello:
    docker:
      - image: cimg/base:current  # Specify Docker image
    steps:
      - checkout  # Checkout your code
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SonarQube scan job using a Node.js image
  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/node:18.17.1  # Updated to a specific Node.js image
    resource_class: small
    steps:
      - checkout  # Checkout your code
      - run:
          name: Run SonarQube Scanner
          command: |
            SONAR_BRANCH="circleci-project-setup"  # or the branch you’re testing
            echo "Using branch: $SONAR_BRANCH"
            npx sonarqube-scanner -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="${SONAR_ORG}" \
              -Dsonar.host.url="https://sonarcloud.io/" \
              -Dsonar.login="${SONAR_TOKEN}" \
              -Dsonar.branch.name="${SONAR_BRANCH}" \
              -Dsonar.sources="." \
              -Dsonar.exclusions="" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  build-and-scan:
    jobs:
      - say-hello
      - sonarqube

